### ISSUE TITLE
Todoist shows only a blank screen

### ISSUE THREAD

**Issue by tkedwards** [flathub/com.todoist.Todoist#70] opened 2023-11-08 21:21 UTC
Thanks for making this Flatpak. But recently I've been unable to use it as no matter what it just shows a blank screen. I've tried deleting the whole ~/.var/app/com.todoist.Todoist/ directory and restarting, including logging in to Todoist again. However same problem happens no matter what.

```
$ flatpak run com.todoist.Todoist
[3:1109/081705.766184:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1109/081706.313156:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1109/081706.313210:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
08:17:06.370 › APPIMAGE env is not defined, current application is not an AppImage
08:17:06.376 › checkForUpdatesAndNotify called, downloadPromise is null
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[52:1109/081706.424415:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[85:1109/081706.456599:ERROR:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.
```

![Screenshot_20231109_081450](https://github.com/flathub/com.todoist.Todoist/assets/1695095/d0d6e13c-e462-440a-8a14-ebb9f91794bb)

**Comment by gekitsuu** [comment] 2023-11-12 16:20
I'm having the same issue but my debug logs look different.

```
[3:1112/111033.204395:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 11:10:33.457: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:10:33.457: Failed to load module "canberra-gtk-module"
[3:1112/111033.467827:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1112/111033.467855:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
11:10:33.492 › APPIMAGE env is not defined, current application is not an AppImage
11:10:33.494 › checkForUpdatesAndNotify called, downloadPromise is null
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[3:1112/111033.572155:ERROR:browser_main_loop.cc(274)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

```

**Comment by gekitsuu** [comment] 2023-11-12 16:32
Looks like maybe it's a duplicate of https://github.com/flathub/com.todoist.Todoist/issues/21 but hard to say without more details. I also tried using the AppImage from Todoist directly and have the same problem so this might not be a Flatpak issue?

**Comment by ecelien** [comment] 2023-11-12 23:54
I was having this issue as well, so I tested the [8.10.0 build](https://github.com/flathub/com.todoist.Todoist/pull/71) and the issue was fixed. Unsure if there are any other issues.

**Comment by gozes** [comment] 2023-11-14 20:12
> I was having this issue as well, so I tested the [8.10.0 build](https://github.com/flathub/com.todoist.Todoist/pull/71) and the issue was fixed. Unsure if there are any other issues.
> 
> Edit: It allowed sign in, but did not stay logged in upon relaunch.

yup I'm having the same issue. just a blank screen after login and if close it I have to sing in again just to get a blank screen

**Comment by jurf** [comment] 2023-11-15 11:54
So does >8.10.0 fix the blank screen issue? If yes, this should be fixed by #73.

**Comment by gekitsuu** [comment] 2023-11-15 12:04
I just installed 8.10.0 and can confirm that fixes it for me.

**Comment by gozes** [comment] 2023-11-15 14:32
> I just installed 8.10.0 and can confirm that fixes it for me.

How do you downgrade?

**Closed** 2023-11-15 16:44 UTC
